### ISSUE TITLE
Package structure & right dependencies

### ISSUE THREAD

**Issue by xavxyz** [portons/react-native-anime#4]
What about easing package development with some tools such as Prettier, Flow, Jest et al. 

I'm thinking about using https://github.com/withspectrum/npm-pkg 😄 

Also specify devDeps / deps / peerDeps

**Comment by xavxyz** [comment]
> Did a quick `git push` but forgot I was on master 🤐 

Changed the structure & updated the readme for local dev: https://github.com/portons/react-native-anime#local-development

![screencast](https://cl.ly/3Y3P0j0P132S/Screen%20Recording%202017-08-16%20at%2009.12%20AM.gif)

**Comment by portons** [comment]
Great work!
